set(camp_headers
include/camp/camp.hpp
include/camp/concepts.hpp
include/camp/defines.hpp
include/camp/detail/sfinae.hpp
include/camp/detail/test.hpp
include/camp/helpers.hpp
include/camp/lambda.hpp
include/camp/list.hpp
include/camp/list/at.hpp
include/camp/list/find_if.hpp
include/camp/list/list.hpp
include/camp/make_unique.hpp
include/camp/map.hpp
include/camp/number.hpp
include/camp/number/if.hpp
include/camp/number/number.hpp
include/camp/resource.hpp
include/camp/resource/cuda.hpp
include/camp/resource/event.hpp
include/camp/resource/hip.hpp
include/camp/resource/host.hpp
include/camp/resource/omp_target.hpp
include/camp/resource/platform.hpp
include/camp/resource/sycl.hpp
include/camp/size.hpp
include/camp/tuple.hpp
include/camp/type_traits.hpp
include/camp/type_traits/is_same.hpp
include/camp/value.hpp
include/camp/value/eval.hpp
)
